// utils/player.ts

export const soccerPlayers = [
  // Real Madrid
  "Kylian Mbappe",
  "Vinicius Junior",
  "Jude Bellingham",
  "Rodrygo",
  "Rodri",
  "Eduardo Camavinga",
  "Aurélien Tchouaméni",
  "Federico Valverde",
  "Dani Carvajal",
  "Antonio Rudiger",
  "Thibaut Courtois",
  "Arda Guler",
  "Brahim Diaz",
  "Endrick",
  "Fran Garcia",
  "Eder Militao",

  // Barcelona
  "Lamine Yamal",
  "Raphinha",
  "Robert Lewandowski",
  "Pedri",
  "Gavi",
  "Frenkie de Jong",
  "Dani Olmo",
  "Fermin Lopez",
  "Pau Cubarsi",
  "Ronald Araujo",
  "Jules Kounde",
  "Alejandro Balde",
  "Ferran Torres",
  "Marc-Andre ter Stegen",

  // Manchester City
  "Erling Haaland",
  "Phil Foden",
  "Kevin De Bruyne",
  "Bernardo Silva",
  "Jack Grealish",
  "Jeremy Doku",
  "Savinho",
  "Ruben Dias",
  "John Stones",
  "Josko Gvardiol",
  "Nathan Ake",
  "Ederson",
  "Mateo Kovacic",
  "Ilkay Gundogan",

  // Manchester United
  "Bruno Fernandes",
  "Marcus Rashford",
  "Alejandro Garnacho",
  "Kobbie Mainoo",
  "Mason Mount",
  "Rasmus Hojlund",
  "Joshua Zirkzee",
  "Matthijs de Ligt",
  "Lisandro Martinez",
  "Luke Shaw",
  "Diogo Dalot",
  "Andre Onana",
  "Casemiro",

  // Liverpool
  "Mohamed Salah",
  "Virgil van Dijk",
  "Trent Alexander-Arnold",
  "Luis Diaz",
  "Darwin Nunez",
  "Cody Gakpo",
  "Dominik Szoboszlai",
  "Alexis Mac Allister",
  "Ryan Gravenberch",
  "Ibrahima Konate",
  "Andy Robertson",
  "Alisson Becker",
  "Curtis Jones",
  "Conor Bradley",

  // Arsenal
  "Bukayo Saka",
  "Martin Odegaard",
  "Declan Rice",
  "William Saliba",
  "Gabriel Magalhaes",
  "Gabriel Martinelli",
  "Kai Havertz",
  "Leandro Trossard",
  "Gabriel Jesus",
  "Ben White",
  "Jorginho",
  "Thomas Partey",
  "David Raya",
  "Riccardo Calafiori",

  // Chelsea
  "Cole Palmer",
  "Nicolas Jackson",
  "Christopher Nkunku",
  "Enzo Fernandez",
  "Moises Caicedo",
  "Romeo Lavia",
  "Mykhailo Mudryk",
  "Noni Madueke",
  "Pedro Neto",
  "Reece James",
  "Levi Colwill",
  "Wesley Fofana",
  "Marc Cucurella",
  "Robert Sanchez",

  // Bayern Munich
  "Harry Kane",
  "Jamal Musiala",
  "Thomas Muller",
  "Leroy Sane",
  "Serge Gnabry",
  "Michael Olise",
  "Kingsley Coman",
  "Joshua Kimmich",
  "Leon Goretzka",
  "Alphonso Davies",
  "Dayot Upamecano",
  "Kim Min-jae",
  "Manuel Neuer",

  // PSG
  "Ousmane Dembele",
  "Khvicha Kvaratskhelia",
  "Achraf Hakimi",
  "Marquinhos",
  "Gianluigi Donnarumma",
  "Vitinha",
  "Warren Zaire-Emery",
  "Bradley Barcola",
  "Desire Doue",
  "Fabian Ruiz",

  // Atletico Madrid
  "Julian Alvarez",
  "Antoine Griezmann",
  "Alexander Sorloth",
  "Rodrigo De Paul",
  "Marcos Llorente",
  "Koke",
  "Jose Maria Gimenez",
  "Jan Oblak",

  // Inter Milan
  "Lautaro Martinez",
  "Marcus Thuram",
  "Nicolo Barella",
  "Hakan Calhanoglu",
  "Alessandro Bastoni",
  "Federico Dimarco",
  "Denzel Dumfries",
  "Yann Sommer",

  // AC Milan
  "Rafael Leao",
  "Christian Pulisic",
  "Theo Hernandez",
  "Mike Maignan",
  "Tijjani Reijnders",
  "Fikayo Tomori",
  "Ruben Loftus-Cheek",

  // Juventus
  "Dusan Vlahovic",
  "Kenan Yildiz",
  "Teun Koopmeiners",
  "Federico Chiesa",
  "Manuel Locatelli",
  "Bremer",
  "Andrea Cambiaso",
  "Wojciech Szczesny",

  // Napoli
  "Romelu Lukaku",
  "Scott McTominay",
  "Khvicha Kvaratskhelia",
  "Matteo Politano",
  "Stanislav Lobotka",

  // Other major players
  "Neymar",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Luis Suarez",
  "Karim Benzema",
  "Luka Modric",
  "Sergio Ramos",
  "Toni Kroos",
  "Sergio Busquets",
  "Angel Di Maria",
  "Paulo Dybala",
  "Lautaro Martinez",
  "Victor Osimhen",
  "Romelu Lukaku",
  "Son Heung-min",
  "Heung-Min Son",
  "James Maddison",
  "Dominic Solanke",
  "Micky van de Ven",
  "Martin Zubimendi",
  "Mikel Oyarzabal",
  "Nico Williams",
  "Dani Carvajal",
  "Mikel Merino",
  "Fermin Lopez",
  "Mason Greenwood",
  "Marcus Thuram",
  "Jonathan David",
  "Victor Boniface",
  "Florian Wirtz",
  "Xavi Simons",
  "Benjamin Sesko",
  "Randal Kolo Muani",
  "Victor Gyokeres",
  "Alexander Isak",
  "Bruno Guimaraes",
  "Sandro Tonali",
  "Anthony Gordon",
  "Harvey Barnes",
  "Ollie Watkins",
  "Morgan Rogers",
  "Moussa Diaby",
  "Christian Eriksen",
  "Wilfried Zaha",
  "Youssouf Fofana",
  "Amine Gouiri",
  "Moussa Dembele",

  // South American stars
  "Vinicius Junior",
  "Rodrygo",
  "Endrick",
  "Gabriel Martinelli",
  "Gabriel Jesus",
  "Richarlison",
  "Gabriel Magalhaes",
  "Casemiro",
  "Alisson",
  "Ederson",
  "Emiliano Martinez",
  "Enzo Fernandez",
  "Alexis Mac Allister",
  "Julian Alvarez",
  "Paulo Dybala",
  "Lautaro Martinez",
  "Nicolas Gonzalez",
  "Federico Valverde",
  "Darwin Nunez",
  "Luis Suarez",

  // Young / emerging players
  "Ethan Nwaneri",
  "Mykhailo Mudryk",
  "Lamine Yamal",
  "Pau Cubarsi",
  "Endrick",
  "Arda Guler",
  "Warren Zaire-Emery",
  "Desire Doue",
  "Jamal Musiala",
  "Alejandro Garnacho",
  "Kobbie Mainoo",
  "Kenan Yildiz",
  "Estevao",
  "Franco Mastantuono",
  "Joao Neves",
  "Leny Yoro",
  "Archie Gray",
  "Kiernan Dewsbury-Hall",
];

export const soccerTeams = [
  "Real Madrid",
  "Barcelona",
  "Manchester United",
  "Manchester City",
  "Arsenal",
  "Liverpool",
  "Chelsea",
  "Tottenham",
  "Newcastle United",
  "Aston Villa",
  "Bayern Munich",
  "Borussia Dortmund",
  "Bayer Leverkusen",
  "RB Leipzig",
  "Paris Saint-Germain",
  "PSG",
  "Marseille",
  "Monaco",
  "Inter Milan",
  "AC Milan",
  "Juventus",
  "Napoli",
  "Roma",
  "Lazio",
  "Atletico Madrid",
  "Sevilla",
  "Real Sociedad",
  "Athletic Bilbao",
  "Valencia",
  "Villarreal",
  "Ajax",
  "PSV Eindhoven",
  "Benfica",
  "Porto",
  "Sporting CP",
  "Galatasaray",
  "Fenerbahce",
  "Al Nassr",
  "Al Hilal",
  "Al Ahli",
  "Inter Miami",
  "LA Galaxy",
  "Boca Juniors",
  "River Plate",
];

export const cricketPlayers = [
  // India
  "Virat Kohli",
  "Rohit Sharma",
  "Jasprit Bumrah",
  "Shubman Gill",
  "Rishabh Pant",
  "KL Rahul",
  "Hardik Pandya",
  "Ravindra Jadeja",
  "Kuldeep Yadav",
  "Mohammed Siraj",
  "Mohammed Shami",
  "Yashasvi Jaiswal",
  "Suryakumar Yadav",
  "Sanju Samson",
  "Shreyas Iyer",
  "Ruturaj Gaikwad",
  "Ishan Kishan",
  "Axar Patel",
  "Arshdeep Singh",
  "Washington Sundar",
  "Rinku Singh",
  "Tilak Varma",
  "Abhishek Sharma",

  // Australia
  "Pat Cummins",
  "Steve Smith",
  "Mitchell Starc",
  "Josh Hazlewood",
  "Nathan Lyon",
  "Travis Head",
  "David Warner",
  "Glenn Maxwell",
  "Mitchell Marsh",
  "Alex Carey",
  "Josh Inglis",
  "Marnus Labuschagne",
  "Cameron Green",

  // England
  "Ben Stokes",
  "Joe Root",
  "Jos Buttler",
  "Harry Brook",
  "Jofra Archer",
  "Mark Wood",
  "Chris Woakes",
  "Liam Livingstone",
  "Phil Salt",
  "Jonny Bairstow",
  "Adil Rashid",
  "Reece Topley",
  "Brydon Carse",

  // Pakistan
  "Babar Azam",
  "Mohammad Rizwan",
  "Shaheen Afridi",
  "Naseem Shah",
  "Haris Rauf",
  "Shadab Khan",
  "Fakhar Zaman",
  "Imam-ul-Haq",
  "Mohammad Amir",
  "Saim Ayub",

  // New Zealand
  "Kane Williamson",
  "Trent Boult",
  "Tim Southee",
  "Devon Conway",
  "Rachin Ravindra",
  "Daryl Mitchell",
  "Glenn Phillips",
  "Mitchell Santner",
  "Matt Henry",

  // South Africa
  "Quinton de Kock",
  "Kagiso Rabada",
  "Anrich Nortje",
  "Aiden Markram",
  "Heinrich Klaasen",
  "David Miller",
  "Marco Jansen",
  "Keshav Maharaj",
  "Temba Bavuma",

  // Sri Lanka / Bangladesh / West Indies
  "Wanindu Hasaranga",
  "Pathum Nissanka",
  "Kusal Mendis",
  "Matheesha Pathirana",
  "Charith Asalanka",
  "Mustafizur Rahman",
  "Shakib Al Hasan",
  "Litton Das",
  "Mehidy Hasan Miraz",
  "Taskin Ahmed",
  "Nicholas Pooran",
  "Andre Russell",
  "Jason Holder",
  "Shimron Hetmyer",
  "Rovman Powell",
];

export const cricketTeams = [
  "India",
  "Australia",
  "England",
  "Pakistan",
  "New Zealand",
  "South Africa",
  "Sri Lanka",
  "Bangladesh",
  "West Indies",
  "Afghanistan",
  "Ireland",
  "Zimbabwe",
  "Royal Challengers Bengaluru",
  "Mumbai Indians",
  "Chennai Super Kings",
  "Kolkata Knight Riders",
  "Rajasthan Royals",
  "Sunrisers Hyderabad",
  "Delhi Capitals",
  "Punjab Kings",
  "Lucknow Super Giants",
  "Gujarat Titans",
];

export const tennisPlayers = [
  // ATP
  "Novak Djokovic",
  "Carlos Alcaraz",
  "Jannik Sinner",
  "Alexander Zverev",
  "Daniil Medvedev",
  "Taylor Fritz",
  "Casper Ruud",
  "Alex de Minaur",
  "Andrey Rublev",
  "Stefanos Tsitsipas",
  "Holger Rune",
  "Tommy Paul",
  "Ben Shelton",
  "Frances Tiafoe",
  "Jack Draper",
  "Grigor Dimitrov",
  "Lorenzo Musetti",
  "Hubert Hurkacz",
  "Karen Khachanov",
  "Sebastian Korda",
  "Francisco Cerundolo",
  "Ugo Humbert",
  "Arthur Fils",
  "Alex Michelsen",
  "Matteo Berrettini",
  "Matteo Arnaldi",
  "Jiri Lehecka",
  "Denis Shapovalov",
  "Felix Auger-Aliassime",
  "Alexander Bublik",
  "Gael Monfils",
  "Richard Gasquet",
  "Stan Wawrinka",
  "Nick Kyrgios",
  "Andy Murray",
  "Rafael Nadal",

  // WTA
  "Aryna Sabalenka",
  "Iga Swiatek",
  "Coco Gauff",
  "Jessica Pegula",
  "Elena Rybakina",
  "Jasmine Paolini",
  "Qinwen Zheng",
  "Mirra Andreeva",
  "Emma Navarro",
  "Madison Keys",
  "Amanda Anisimova",
  "Danielle Collins",
  "Barbora Krejcikova",
  "Marketa Vondrousova",
  "Daria Kasatkina",
  "Elina Svitolina",
  "Paula Badosa",
  "Beatriz Haddad Maia",
  "Jelena Ostapenko",
  "Victoria Azarenka",
  "Naomi Osaka",
  "Emma Raducanu",
  "Karolina Muchova",
  "Linda Noskova",
  "Leylah Fernandez",
  "Donna Vekic",
  "Maria Sakkari",
  "Sofia Kenin",
  "Katie Boulter",
  "Elise Mertens",
  "Ons Jabeur",
  "Karolina Pliskova",
  "Petra Kvitova",
  "Venus Williams",
  "Serena Williams",
];

export const tennisTeams: string[] = [];